import type { ProjectInput } from "@/content/projects/types";

export const enProjectItems: ProjectInput[] = [
  {
    id: "onepage-institucional-aza8",
    title: "Aza8 Institutional One-Page Site",
    organizationId: "aza8-agency",
    date: "Oct.2025",
    links: {
      official: { url: "https://www.aza8.com.br/", expired: true },
      preview: { url: "https://agencia-aza8-website.vercel.app/" },
    },
    summary: [
      "Institutional one-page site built with React and Next.js using TypeScript, reflecting the brand's positioning and purpose.",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "TypeScript",
      "Tailwind",
      "Node.js",
      "Vercel",
      "Git",
      "Responsive Design",
      "Performance",
    ],
    type: ["One Page", "Site Institucional"],
  },
  {
    id: "landing-page-sao-lucas-medical-tech",
    title: "São Lucas Hospital Landing Page – Medical Tech",
    organizationId: "aza8-agency",
    date: "May.2025",
    links: {
      preview: { url: "https://aza8-sao-lucas-landing-page.vercel.app/" },
    },
    summary: [
      "Institutional landing page built with Vue.js, focused on SEO, performance, and responsiveness.",
    ],
    technologies: [
      "Vue.js",
      "JavaScript",
      "Sass",
      "Node.js",
      "Git",
      "SEO",
      "Performance",
      "Responsive Design",
    ],
    type: ["Landing Page", "Site Institucional"],
    highlight: true,
  },
  {
    id: "landing-page-vpl-protecao-veicular",
    title: "VPL Vehicle Protection Landing Page",
    organizationId: "aza8-agency",
    date: "Apr.2025",
    links: { preview: { url: "https://vpl-website.vercel.app/" } },
    summary: [
      "Institutional and commercial landing page built with Vue.js, focused on SEO and lead generation.",
    ],
    technologies: [
      "Vue.js",
      "JavaScript",
      "Sass",
      "Node.js",
      "Git",
      "SEO",
      "Performance",
      "Responsive Design",
    ],
    type: ["Landing Page", "Site Institucional"],
  },
  {
    id: "site-corporativo-banco-digimais",
    title: "Banco Digimais Corporate Website",
    organizationId: "aza8-agency",
    date: "Feb.2025",
    links: {
      official: { url: "https://www.bancodigimais.com.br/", expired: false },
      preview: { url: "https://banco-digimais-website.vercel.app/" },
    },
    summary: [
      "Corporate website built with React and Next.js, featuring multiple institutional pages with a focus on performance, accessibility, and SEO.",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "TypeScript",
      "Tailwind",
      "Node.js",
      "Vercel",
      "Git",
      "SEO",
      "Accessibility",
      "Performance",
    ],
    type: ["Site Corporativo", "CMS"],
    highlight: true,
  },
  {
    id: "cms-artec-revestimentos",
    title: "Artec Revestimentos Institutional CMS",
    organizationId: "aza8-agency",
    date: "Feb.2023",
    links: {
      official: { url: "https://artecrevestimentos.com.br/", expired: false },
    },
    summary: [
      "Corporate CMS built with Vue.js, Nuxt, and Strapi, featuring a product catalog, blog, and headless admin panel.",
    ],
    technologies: [
      "Vue.js",
      "Nuxt.js",
      "TypeScript",
      "Tailwind",
      "Strapi",
      "Node.js",
      "REST API",
      "Git",
      "Performance",
    ],
    type: ["CMS", "Site Corporativo", "Headless CMS"],
    highlight: true,
  },
  {
    id: "cms-institucional-para-m2b-pro",
    title: "Institutional CMS for M2B Pro",
    organizationId: "aza8-agency",
    date: "Nov.2021",
    links: { official: { url: "https://www.m2bpro.com.br", expired: false } },
    summary: [
      "Development of a corporate CMS with React and Strapi, focused on performance and headless architecture.",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "TypeScript",
      "Tailwind",
      "Strapi",
      "Node.js",
      "AWS",
      "Git",
      "Clean Architecture",
    ],
    type: ["CMS", "Site Corporativo", "Headless CMS"],
    featured: true,
    highlight: true,
  },
  {
    id: "site-corporativo-kt-retailing",
    title: "KT Retailing Corporate Website",
    organizationId: "aza8-agency",
    date: "Jun.2021",
    links: { official: { url: "https://kt.com.br", expired: false } },
    summary: [
      "Institutional website with a custom CMS built with Vue.js and Strapi, highlighting performance and dynamic content.",
    ],
    technologies: [
      "Vue.js",
      "TypeScript",
      "Strapi",
      "Tailwind",
      "Node.js",
      "Git",
      "Performance",
      "Clean Code",
    ],
    type: ["CMS", "Site Corporativo", "Headless CMS"],
    highlight: true,
  },
  {
    id: "site-estatico-casa-cortinas-persianas",
    title: "Casa Cortinas & Persianas Static Website",
    organizationId: "aza8-agency",
    date: "Mar.2021",
    links: {
      official: {
        url: "https://produtos.casacortinasepersianas.com.br/",
        expired: false,
      },
    },
    summary: [
      "Institutional website built with Vue.js and Nuxt using static generation (SSG), focused on lightweight performance.",
    ],
    technologies: [
      "Vue.js",
      "Nuxt.js",
      "JavaScript",
      "Tailwind",
      "Node.js",
      "Git",
      "Performance",
      "Responsive Design",
    ],
    type: ["Site Institucional"],
  },
  {
    id: "memorial-avarc-homenagem-covid19",
    title: "Avarc Memorial - Tribute to COVID-19 Victims",
    organizationId: "ministerio-publico-sp",
    date: "Feb.2021",
    links: {
      official: { url: "https://www.memorialavarc.com.br/", expired: false },
    },
    summary: [
      "Volunteer institutional website built with Vue.js and Nuxt, focused on accessibility and dynamic content integration.",
    ],
    technologies: [
      "Vue.js",
      "Nuxt.js",
      "JavaScript",
      "Sass",
      "Node.js",
      "Git",
      "Responsive Design",
      "Accessibility",
    ],
    type: ["Site Institucional", "CMS"],
    highlight: true,
  },
  {
    id: "landing-page-promocional-good-spine",
    title: "Good Spine Promotional Landing Page",
    date: "Apr.2021",
    links: {
      official: { url: "https://travesseiro.goodspine.com.br", expired: false },
    },
    summary: [
      "Landing page focused on conversion for selling orthopedic products, optimized for SEO and performance.",
    ],
    technologies: [
      "Vue.js",
      "Nuxt.js",
      "TypeScript",
      "Tailwind",
      "Sass",
      "Git",
      "UX",
      "SEO",
      "Landing Page",
    ],
    type: ["Landing Page"],
    highlight: true,
  },
  {
    id: "site-institucional-loopa-digital",
    title: "Loopa Digital Institutional Website",
    organizationId: "cave-digital-agency",
    date: "Feb.2019",
    links: { official: { url: "https://www.loopa.digital", expired: false } },
    summary: [
      "Development of an institutional website on WordPress with a custom theme, focused on SEO.",
    ],
    technologies: [
      "WordPress",
      "PHP",
      "JavaScript",
      "Sass",
      "Git",
      "SEO",
      "Responsive Design",
    ],
    type: ["CMS", "Site Institucional"],
  },
  {
    id: "site-oficial-galeria-do-rock",
    title: "Galeria do Rock Official Website",
    organizationId: "cave-digital-agency",
    date: "Jan.2019",
    links: {
      official: { url: "https://www.galeriadorock.com.br", expired: false },
    },
    summary: [
      "Institutional WordPress website for Galeria do Rock, a cultural icon of São Paulo.",
    ],
    technologies: [
      "WordPress",
      "PHP",
      "JavaScript",
      "Sass",
      "SEO",
      "Performance",
      "Accessibility",
    ],
    type: ["CMS", "Site Institucional"],
    highlight: true,
  },
  {
    id: "blog-autoral-juliao-coelho",
    title: "Julião Coelho Personal Blog",
    organizationId: "cave-digital-agency",
    date: "Nov.2018",
    links: {
      official: { url: "https://www.juliaocoelho.com.br", expired: false },
    },
    summary: [
      "Personal blog built on WordPress with responsive design, focused on branding and performance.",
    ],
    technologies: [
      "WordPress",
      "PHP",
      "JavaScript",
      "Sass",
      "SEO",
      "Performance",
      "Blog",
      "Accessibility",
    ],
    type: ["Blog", "CMS"],
  },
  {
    id: "landing-page-covabra",
    title: "Covabra Landing Page",
    organizationId: "cave-digital-agency",
    date: "Sep.2018",
    summary: [
      "Promotional landing page for the Covabra retail chain, optimized for digital campaigns.",
    ],
    technologies: [
      "JavaScript",
      "Node.js",
      "Gulp",
      "Sass",
      "BemCSS",
      "Git",
      "Performance",
      "Landing Page",
    ],
    type: ["Landing Page"],
  },
  {
    id: "landing-corporativa-unic",
    title: "UNIC Corporate Landing Page",
    organizationId: "cave-digital-agency",
    date: "Aug.2018",
    links: {
      official: { url: "https://www.unic-corporativos.com.br", expired: false },
    },
    summary: [
      "Corporate landing page focused on showcasing services and performance optimization.",
    ],
    technologies: [
      "JavaScript",
      "Node.js",
      "Gulp",
      "Sass",
      "BemCSS",
      "Git",
      "Performance",
      "UX",
    ],
    type: ["Landing Page", "Site Corporativo"],
  },
  {
    id: "landing-animada-metlycs",
    title: "Metlycs Animated Landing Page",
    organizationId: "l4u-agency",
    date: "Mar.2018",
    links: { official: { url: "https://www.metlycs.com.br", expired: false } },
    summary: [
      "Dynamic landing page with animations and interactions, developed for promotional campaigns.",
    ],
    technologies: [
      "Vue.js",
      "Node.js",
      "Pug.js",
      "CSS animations",
      "Webpack",
      "Git",
      "UX",
      "Performance",
    ],
    type: ["Landing Page", "One Page"],
    highlight: true,
  },
  {
    id: "site-institucional-dvl",
    title: "DVL Institutional Website",
    organizationId: "l4u-agency",
    date: "Jan.2018",
    links: {
      official: { url: "https://www.constelacaodvl.com.br", expired: false },
    },
    summary: [
      "Development of an institutional website focused on digital identity and performance.",
    ],
    technologies: [
      "JavaScript",
      "Node.js",
      "Heroku",
      "Sass",
      "BemCSS",
      "Git",
      "SEO",
      "Performance",
    ],
    type: ["Site Institucional"],
  },
  {
    id: "portal-de-franquias-dia",
    title: "DIA Franchise Portal",
    organizationId: "l4u-agency",
    date: "Oct.2017",
    links: {
      official: { url: "https://www.franquiadia.com.br", expired: false },
    },
    summary: [
      "WordPress portal for showcasing and attracting franchises for the DIA brand.",
    ],
    technologies: [
      "WordPress",
      "PHP",
      "JavaScript",
      "Sass",
      "SEO",
      "Performance",
      "CMS",
    ],
    type: ["CMS", "Portal"],
    highlight: true,
  },
];
